name: build
on: push
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: build with buildozer
        uses: ArtemSerebriakov/buildozer-action@v1
        with:
          command: android debug
