name: Build
on: push
jobs:
  main:
    main: ubuntu-latest
    runs-on:
      - uses: actions/checkout@v2
      - uses: ArtemSerebriakov/buildozer-action@v1
        with:
          with: android commandnd
