name: build
on: push
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: setup python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: install buildozer
        run: |
          pip install --user --upgrade buildozer cython
          echo "$HOME/.local/bin" >> $GITHUB_PATH
      - name: build apk
        run: buildozer android debug

